name: Billyrushstudio
favicon: null
layout_spectrum: 0.801327467430383
typography_spectrum: 0.7846955719869584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.059045145055279136
  lightness: 0.6395655765663832
  saturation: 0.2268802928738296
  rhythmicContrast: 0.6001437082886696
purpose: []
